#!/usr/bin/python3
# Run this with --help to see available options for tracing and debugging
# See https://github.com/cockpit-project/cockpit/blob/master/test/common/testlib.py
# "class Browser" and "class MachineCase" for the available API.

import os
import sys

# import Cockpit's machinery for test VMs and its browser test API
TEST_DIR = os.path.dirname(__file__)
sys.path.append(os.path.join(TEST_DIR, "common"))
sys.path.append(os.path.join(os.path.dirname(TEST_DIR), "bots/machine"))
import testlib


class TestApplication(testlib.MachineCase):
    def createCertificate(self, nickName):
        m = self.machine

        m.execute("selfsign-getcert request -d /etc/pki/nssdb -n {0}".format(nickName))

    def testBasic(self):
        b = self.browser
        m = self.machine

        self.createCertificate("Server-Cert")

        self.login_and_go("/certificates")
        # verify expected heading
        b.wait_text(".container-fluid h2", "Certificates")


if __name__ == '__main__':
    testlib.test_main()
