#!/usr/bin/python3 -cimport os, sys; os.execv(os.path.dirname(sys.argv[1]) + "/common/pywrap", sys.argv)
# Run this with --help to see available options for tracing and debugging
# See https://github.com/cockpit-project/cockpit/blob/main/test/common/testlib.py
# "class Browser" and "class MachineCase" for the available API.

import datetime
import time

# import Cockpit's machinery for test VMs and its browser test API
import testlib


@testlib.nondestructive
class TestApplication(testlib.MachineCase):
    def setUp(self):
        super().setUp()

        # When we disconnect while certmonger wants to tell us something
        self.allow_journal_messages("org.fedorahosted.certmonger: couldn't introspect /org/fedorahosted/certmonger/.*Remote peer disconnected")

        # Restore the nssdb as it keeps an old entry with the principal name which if the test
        # runs twice will be generated with a principal name which we don't want.
        self.restore_dir("/etc/pki/nssdb", restart_unit="certmonger")

    def cleanupCertificate(self, cert_name, db_path):
        output = self.machine.execute(f"getcert list -d {db_path} -n {cert_name} || exit 0")
        if cert_name in output:
            self.machine.execute(f"selfsign-getcert stop-tracking -d {db_path} -n {cert_name}")

    def cleanupFileCertificate(self, cert_path, key_path):
        output = self.machine.execute(f"getcert list -f {cert_path} || exit 0")
        if cert_path in output:
            self.machine.execute(f"selfsign-getcert stop-tracking -k {key_path} -f {cert_path}")
            self.machine.execute(f"rm {key_path} {cert_path} || exit 0")

    def selectKeyTab(self, row):
        self.browser.click(f"#expanded-content{row} li:nth-child(2) button")

    def selectCertificateTab(self, row):
        self.browser.click(f"#expanded-content{row} li:nth-child(3) button")

    def testEmptyState(self):
        b = self.browser
        m = self.machine

        # Check service was started automatically when when first entering certficates page
        m.execute("systemctl stop certmonger.service")

        self.login_and_go("/certificates")

        b.wait_visible("table .pf-v5-c-empty-state")
        b.wait_in_text(".ct-table-header h3", "Certificates")

        # Check Empty State is present if service was stopped when certificates page is open
        # Mask the unit so it doesn't get activated if requests are still running.
        m.execute("systemctl mask --runtime certmonger")
        m.execute("systemctl stop certmonger.service")
        b.wait_visible(".pf-v5-c-empty-state")
        m.execute("systemctl unmask --runtime certmonger")

        # Check Starting service from UI works
        b.click(".pf-v5-c-empty-state button:contains(Start the certificate service)")

        b.wait_visible("table .pf-v5-c-empty-state")
        b.wait_in_text(".ct-table-header h3", "Certificates")

        # Check check stopping and starting UI from command line reflects state of UI
        m.execute("systemctl stop certmonger.service")
        b.wait_visible(".pf-v5-c-empty-state")

        m.execute("systemctl start certmonger.service")
        b.wait_visible("table .pf-v5-c-empty-state")
        b.wait_in_text(".ct-table-header h3", "Certificates")

    def testNoCertificates(self):
        b = self.browser

        self.login_and_go("/certificates")
        # verify expected heading
        b.wait_in_text(".ct-table-header h3", "Certificates")
        b.wait_in_text(".ct-table-empty tr td", "No certificate is tracked on this host")

    def testWarningExpiredCert(self):
        b = self.browser
        m = self.machine

        self.restore_file('/etc/certmonger/certmonger.conf', "systemctl restart certmonger")

        cert_name = "Server-Cert1"
        db_path = "/etc/pki/nssdb"
        # Request certificate without automatical renewal
        m.execute(f"selfsign-getcert request -d {db_path} -n {cert_name} -R")
        self.addCleanup(self.cleanupCertificate, cert_name, db_path)

        self.login_and_go("/certificates")
        # Verify expected heading
        b.wait_in_text(".ct-table-header h3", "Certificates")

        # Check certificate validity doesn't contain a warning
        b.wait_not_present("#certificate-0-validity .ct-icon-exclamation-triangle")

        # Remove cert
        m.execute(f"selfsign-getcert stop-tracking -d {db_path} -n {cert_name}")
        self.browser.reload()
        self.browser.enter_page('/certificates')

        # Change validity of new certs to 2 weeks
        cert_name = 'Server-Cert2'
        m.execute("echo -e '[selfsign]\nvalidity_period = 2w' > /etc/certmonger/certmonger.conf")
        m.execute("systemctl restart certmonger.service")
        m.execute(f"selfsign-getcert request -d {db_path} -n {cert_name} -R")
        self.addCleanup(self.cleanupCertificate, cert_name, db_path)

        # Check warning about near expiration
        b.wait_in_text(".ct-table-header h3", "Certificates")
        b.wait_visible("#certificate-0-validity .ct-icon-exclamation-triangle")

        # Remove cert
        m.execute(f"selfsign-getcert stop-tracking -d {db_path} -n {cert_name}")
        self.browser.reload()
        self.browser.enter_page('/certificates')

        # Change validity of new certs to 1 second
        m.execute("echo -e '[selfsign]\nvalidity_period = 1s' > /etc/certmonger/certmonger.conf")
        m.execute("systemctl restart certmonger.service")
        # Wait 4 seconds after requesting which should make the certificate already expired
        # TODO requesting itself takes some time and 4 seconds might now be enough.
        # Fix this if race condition starts to show up
        cert_name = "Server-Cert3"
        m.execute(f"selfsign-getcert request -d {db_path} -n {cert_name} -R && sleep 4")
        self.addCleanup(self.cleanupCertificate, cert_name, db_path)

        self.browser.reload()
        self.browser.enter_page('/certificates')
        # Check error about expired certificate
        b.wait_in_text(".ct-table-header h3", "Certificates")
        b.wait_visible("#certificate-0-validity .ct-icon-times-circle")

    def testModifyAutorenewal(self):
        b = self.browser
        m = self.machine

        cert_name = "Server-Cert"
        db_path = "/etc/pki/nssdb"
        m.execute(f"selfsign-getcert request -d {db_path} -n {cert_name}")
        self.addCleanup(self.cleanupCertificate, cert_name, db_path)

        self.login_and_go("/certificates")

        b.wait_in_text(".ct-table-header h3", "Certificates")
        b.wait_in_text("#certificate-0-name", cert_name)

        b.click("button#expand-togglecertificate-0")
        # Check General tab
        renewal_state = b.get_checked("#certificate-0-general-autorenewal")
        b.set_checked("#certificate-0-general-autorenewal", not renewal_state)
        b.wait_visible("#certificate-0-general-autorenewal:not(:checked)")

        command_output = m.execute(f"selfsign-getcert list -d {db_path} -n {cert_name} | grep 'auto-renew:' | awk '{{print $2}}'")
        if not renewal_state:  # renewal state updated to the opposite
            self.assertEqual(command_output, "yes\n")
        else:
            self.assertEqual(command_output, "no\n")

    def testNssdbCert(self):
        b = self.browser
        m = self.machine

        date_now = datetime.datetime.now()
        next_year = date_now.replace(year=date_now.year + 1)
        next_year_str = next_year.strftime('%-m/%-d/%Y')

        cert_name = "Server-Cert"
        db_path = "/etc/pki/nssdb"
        m.execute(f"selfsign-getcert request -d {db_path} -n {cert_name}")
        self.addCleanup(self.cleanupCertificate, cert_name, db_path)

        self.login_and_go("/certificates")
        # Verify expected heading
        b.wait_in_text(".ct-table-header h3", "Certificates")

        # Check cert header
        b.wait_in_text("#certificate-0-name", cert_name)
        b.wait_in_text("#certificate-0-validity", f"Auto-renews before {next_year_str}")
        b.wait_in_text("#certificate-0-ca", "Self-signed")

        b.click("button#expand-togglecertificate-0")
        # Check General tab
        b.wait_in_text("#certificate-0-general-status", "Monitoring")
        b.wait_in_text("#certificate-0-general-ca", "Self-signed")
        b.wait_in_text("#certificate-0-general-validity", f" to {next_year_str}")  # TODO better date handling
        self.assertEqual(b.get_checked("#certificate-0-general-autorenewal"), True)

        self.selectKeyTab(0)
        # Check Key tab
        b.wait_in_text("#certificate-0-key-nickname", cert_name)
        b.wait_in_text("#certificate-0-key-type", "RSA")
        b.wait_in_text("#certificate-0-key-token", "NSS Certificate DB")
        b.wait_in_text("#certificate-0-key-storage", "NSSDB")
        b.wait_in_text("#certificate-0-key-location", db_path)

        self.selectCertificateTab(0)
        # Check Cert tab
        b.wait_in_text("#certificate-0-cert-nickname", cert_name)
        b.wait_in_text("#certificate-0-cert-token", "NSS Certificate DB")
        b.wait_in_text("#certificate-0-cert-storage", "NSSDB")
        b.wait_in_text("#certificate-0-cert-location", db_path)

    # Test subscription to Dbus PropertyChanged signal which is emmitted when property of
    # dbus object is changed
    # Check whetever UI is dynamically updated
    def testDbusPropertyChanged(self):
        b = self.browser
        m = self.machine

        cert_path = "/etc/pki/tls/certs/myCert.cert"
        key_path = "/etc/pki/tls/private/myKey.key"
        m.execute(f"selfsign-getcert request -f {cert_path} -k {key_path}")
        self.addCleanup(self.cleanupFileCertificate, cert_path, key_path)

        self.login_and_go("/certificates")

        b.click("button#expand-togglecertificate-0")
        # Check General tab
        validity = b.text("#certificate-0-general-validity")

        # If we resubmit in the same minute in which we created the certificate no visual change
        time.sleep(61)

        # Renew a certificate
        m.execute(f"selfsign-getcert resubmit -f {cert_path}")
        # Check validity time changed
        b.wait_not_in_text("#certificate-0-general-validity", validity)

    def testFileCert(self):
        b = self.browser
        m = self.machine

        date_now = datetime.datetime.now()
        next_year = date_now.replace(year=date_now.year + 1)
        next_year_str = next_year.strftime('%-m/%-d/%Y')

        cert_path = "/etc/pki/tls/certs/myCert.cert"
        key_path = "/etc/pki/tls/private/myKey.key"
        m.execute(f"selfsign-getcert request -f {cert_path} -k {key_path}")
        self.addCleanup(self.cleanupFileCertificate, cert_path, key_path)

        self.login_and_go("/certificates")
        # Verify expected heading
        b.wait_in_text(".ct-table-header h3", "Certificates")

        # Check cert header
        b.wait_in_text("#certificate-0-validity", f"Auto-renews before {next_year_str}")
        b.wait_in_text("#certificate-0-ca", "Self-signed")

        b.click("button#expand-togglecertificate-0")
        # Check General tab
        b.wait_in_text("#certificate-0-general-status", "Monitoring")
        b.wait_in_text("#certificate-0-general-ca", "Self-signed")
        b.wait_in_text("#certificate-0-general-validity", f" to {next_year_str}")
        self.assertEqual(b.get_checked("#certificate-0-general-autorenewal"), True)

        # Check Key tab
        self.selectKeyTab(0)
        b.wait_in_text("#certificate-0-key-type", "RSA")
        b.wait_in_text("#certificate-0-key-storage", "FILE")
        b.wait_in_text("#certificate-0-key-location", key_path)

        self.selectCertificateTab(0)
        # Check Cert tab
        b.wait_in_text("#certificate-0-cert-storage", "FILE")
        b.wait_in_text("#certificate-0-cert-location", cert_path)

    def testRemoveCert(self):
        b = self.browser
        m = self.machine

        # Test removal of NSSDB-stored certificate
        cert_name = "Server-Cert"
        db_path = "/etc/pki/nssdb"
        m.execute(f"selfsign-getcert request -d {db_path} -n {cert_name}")
        self.addCleanup(self.cleanupCertificate, cert_name, db_path)

        cert_name2 = "Server-Cert2"
        m.execute(f"selfsign-getcert request -d {db_path} -n {cert_name2}")
        self.addCleanup(self.cleanupCertificate, cert_name2, db_path)

        self.login_and_go("/certificates")
        b.wait_in_text(".ct-table-header h3", "Certificates")

        # Check certificate is present
        b.wait_in_text("#certificate-0-name", cert_name)

        # Remove certificate
        b.click("#certificate-0-action-kebab button")
        b.click("#certificate-0-remove a")
        b.wait_in_text(".pf-v5-c-modal-box__title", "Remove certificate")
        b.wait_not_present("#certificate-0-delete-files")  # Check delete files option is not present for NSSDB-stored certificate
        b.click(".pf-v5-c-modal-box__footer button:contains(Remove)")
        b.wait_not_present(".pf-v5-c-modal-box")

        b.wait_in_text("#certificate-0-name", cert_name2)

        # Remove second certificate
        b.click("#certificate-0-action-kebab button")
        b.click("#certificate-0-remove a")
        b.wait_in_text(".pf-v5-c-modal-box__title", "Remove certificate")
        b.click(".pf-v5-c-modal-box__footer button:contains(Remove)")
        b.wait_not_present(".pf-v5-c-modal-box")

        # Check cert is not present
        b.wait_not_present("#certificate-0-name")

        # Test removal of files based certificate. Remove without deleting files
        cert_path = "/etc/pki/tls/certs/myCert.cert"
        key_path = "/etc/pki/tls/private/myKey.key"
        m.execute(f"selfsign-getcert request -f {cert_path} -k {key_path}")
        self.addCleanup(self.cleanupFileCertificate, cert_path, key_path)

        self.login_and_go("/certificates")
        b.wait_in_text(".ct-table-header h3", "Certificates")

        # Check certificate is present
        b.wait_visible("#certificate-0-name")

        # Remove certificate
        b.click("#certificate-0-action-kebab button")
        b.click("#certificate-0-remove a")
        b.wait_in_text(".pf-v5-c-modal-box__title", "Remove certificate")
        b.wait_visible("#certificate-0-delete-files")  # Check delete files option is not present for NSSDB-stored certificate
        b.click(".pf-v5-c-modal-box__footer button:contains(Remove)")
        b.wait_not_present(".pf-v5-c-modal-box")

        # Check cert is not present
        b.wait_not_present("#certificate-0-name")
        # Check files were left untouched
        m.execute(f"test -f {cert_path}; test -f {key_path}")

        # Test removal of files based certificate. Remove without deleting files
        cert_path = "/etc/pki/tls/certs/myCert.cert"
        key_path = "/etc/pki/tls/private/myKey.key"
        m.execute(f"selfsign-getcert request -f {cert_path} -k {key_path}")
        self.addCleanup(self.cleanupFileCertificate, cert_path, key_path)

        self.login_and_go("/certificates")
        b.wait_in_text(".ct-table-header h3", "Certificates")

        # Check certificate is present
        b.wait_visible("#certificate-0-name")

        # Remove certificate
        b.click("#certificate-0-action-kebab button")
        b.click("#certificate-0-remove a")
        b.wait_in_text(".pf-v5-c-modal-box__title", "Remove certificate")
        b.click("#certificate-0-delete-files")  # Check delete files option is not present for NSSDB-stored certificate
        b.click(".pf-v5-c-modal-box__footer button:contains(Remove)")
        b.wait_not_present(".pf-v5-c-modal-box")

        # Check cert is not present
        b.wait_not_present("#certificate-0-name")
        # Check files were deleted
        m.execute(f"! test -f {cert_path}; ! test -f {key_path}")

    def testRequestCert(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/certificates")
        # verify expected heading
        b.wait_in_text(".ct-table-header h3", "Certificates")

        class RequestCertDialog(object):
            def __init__(
                self, test_obj, ca="SelfSign", storage_type="NSSDB", nickname=None,
                key_path="", cert_path="", subject_name=None, dns_name=None, principal_name=None
            ):
                self.test_obj = test_obj
                self.ca = ca
                self.storage_type = storage_type
                self.nickname = nickname
                self.cert_path = cert_path
                self.key_path = key_path
                self.subject_name = subject_name
                self.dns_name = dns_name
                self.principal_name = principal_name

            def execute(self):
                self.open()
                self.fill()
                self.create()
                self.verify_frontend()
                self.verify_backend()
                self.cleanup()

            def open(self):
                b.click("#request-certificate-action")
                b.wait_in_text(".pf-v5-c-modal-box .pf-v5-c-modal-box__header .pf-v5-c-modal-box__title", "Request certificate")

            def fill(self):
                if self.ca:
                    b.select_from_dropdown("#ca", self.ca)
                if self.storage_type:
                    b.click(f".pf-v5-c-radio__input + label:contains({self.storage_type})")

                if self.storage_type == "NSSDB":
                    if self.nickname:
                        b.set_input_text("#nickname", self.nickname)
                else:
                    b.set_input_text("input[placeholder='Path to store the certificate']", self.cert_path)
                    b.click("#cert-file .pf-v5-c-select__menu-item")
                    b.set_input_text("input[placeholder='Path to store the generated key or to an existing key']", self.key_path)
                    b.click("#key-file .pf-v5-c-select__menu-item")

                if self.subject_name or self.dns_name or self.principal_name:
                    b.click("#set-signing-parameters")

                    if self.subject_name:
                        b.set_input_text("#subject-name", self.subject_name)
                    if self.dns_name:
                        b.set_input_text("#dns-name", self.dns_name)
                    if self.principal_name:
                        b.set_input_text("#principal-name", self.principal_name)

            def cancel(self):
                b.click(".pf-v5-c-modal-box__footer button:contains(Cancel)")
                b.wait_not_present(".pf-v5-c-modal-box")

            def create(self):
                b.click(".pf-v5-c-modal-box__footer button:contains(Request)")
                b.wait_not_present(".pf-v5-c-modal-box")
                if self.storage_type == "NSSDB":
                    # First issued certificate uses an autogenerated nickname
                    nickname = self.nickname if self.nickname else b.text("#certificate-0-name")
                    self.test_obj.addCleanup(self.test_obj.cleanupCertificate, nickname, self.cert_path)
                else:
                    self.test_obj.addCleanup(self.test_obj.cleanupFileCertificate, self.cert_path, self.key_path)
                time.sleep(4)  # Certificate enrollment takes some time

            def verify_frontend(self):
                if not self.ca:
                    self.ca = b.text("#certificate-0-ca")
                if self.storage_type == "NSSDB" and not self.nickname:
                    self.nickname = b.text("#certificate-0-name")

                b.click("button#expand-togglecertificate-0")

                if self.subject_name:
                    b.wait_in_text("#certificate-0-general-subject", self.subject_name)
                if self.principal_name:
                    b.wait_in_text("#certificate-0-general-principal", self.principal_name)
                if self.dns_name:
                    b.wait_in_text("#certificate-0-general-dns", self.dns_name)

                if self.storage_type == "NSSDB":
                    b.wait_in_text("#certificate-0-name", self.nickname)
                    self.test_obj.selectCertificateTab(0)
                    b.wait_in_text("#certificate-0-cert-storage", "NSSDB")
                    self.test_obj.selectKeyTab(0)
                    b.wait_in_text("#certificate-0-key-storage", "NSSDB")
                else:
                    if self.key_path:
                        self.test_obj.selectKeyTab(0)
                        b.wait_in_text("#certificate-0-key-location", self.key_path)
                    if self.cert_path:
                        self.test_obj.selectCertificateTab(0)
                        b.wait_in_text("#certificate-0-cert-location", self.cert_path)

            def verify_backend(self):

                if self.storage_type == "NSSDB":
                    command_output = m.execute(f"getcert list -d /etc/pki/nssdb -n {self.nickname} -c {self.ca} | grep 'key pair storage:' | awk '{{print $4}}'")
                    self.test_obj.assertIn(command_output.strip(), f"type=NSSDB,location='/etc/pki/nssdb',nickname='{self.nickname}',token='NSS\n")
                    command_output = m.execute(f"getcert list -d /etc/pki/nssdb -n {self.nickname} -c {self.ca} | grep 'certificate:' | awk '{{print $2}}'")
                    self.test_obj.assertIn(command_output.strip(), f"type=NSSDB,location='/etc/pki/nssdb',nickname='{self.nickname}',token='NSS\n")
                elif self.storage_type == "File":
                    command_output = m.execute(f"getcert list -f {self.cert_path} -c {self.ca} | grep 'key pair storage:' | awk '{{print $4}}'")
                    self.test_obj.assertEqual(command_output, f"type=FILE,location='{self.key_path}'\n")
                    command_output = m.execute(f"getcert list -f {self.cert_path} -c {self.ca} | grep 'certificate:' | awk '{{print $2}}'")
                    self.test_obj.assertEqual(command_output, f"type=FILE,location='{self.cert_path}'\n")

            def cleanup(self):
                if self.storage_type == "NSSDB":
                    m.execute(f"getcert stop-tracking -d /etc/pki/nssdb -n {self.nickname} -c {self.ca}")
                else:
                    m.execute(f"getcert stop-tracking -f {self.cert_path} -k {self.key_path} -c {self.ca}")
                b.reload()
                b.enter_page('/certificates')

        # Test certificate request with everything pre-generated.
        RequestCertDialog(
            self,
        ).execute()

        # Test request of basic NSSDB stored certificate
        RequestCertDialog(
            self,
            ca="SelfSign",
            nickname="testcert1",
            storage_type="NSSDB",
        ).execute()

        # Test request of basic system file stored certificate
        RequestCertDialog(
            self,
            ca="SelfSign",
            cert_path="/etc/pki/tls/certs/testcert2.cert",
            key_path="/etc/pki/tls/private/testkey2.key",
            storage_type="File",
        ).execute()

        # Test subject name, dns name and principal name
        RequestCertDialog(
            self,
            nickname="testcert3",
            storage_type="NSSDB",
            subject_name="TEST_HOSTNAME",
            dns_name="example.com",
            principal_name="HTTP/TEST_HOSTNAME",
        ).execute()

    def testImportCert(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/certificates")
        # verify expected heading
        b.wait_in_text(".ct-table-header h3", "Certificates")

        class ImportCertDialog(object):
            def __init__(
                self, test_obj, ca="SelfSign", storage_type="File",
                key_path="", cert_path="", subject_name=None, dns_name=None, principal_name=None,
            ):
                self.test_obj = test_obj
                self.ca = ca
                self.storage_type = storage_type
                self.cert_path = cert_path
                self.key_path = key_path
                self.subject_name = subject_name
                self.dns_name = dns_name
                self.principal_name = principal_name

            def execute(self):
                self.open()
                self.fill()
                self.create()
                self.verify_backend()
                self.verify_frontend()
                self.cleanup()

            def open(self):
                b.click("#import-certificate-action")
                b.wait_in_text(".pf-v5-c-modal-box .pf-v5-c-modal-box__header .pf-v5-c-modal-box__title", "Import certificate")

            def fill(self):
                if self.ca:
                    b.select_from_dropdown("#ca", self.ca)

                b.set_input_text("input[placeholder='Path to an existing certificate file']", self.cert_path)
                b.click("#cert-file .pf-v5-c-select__menu-item")
                b.set_input_text("input[placeholder='Path to an existing key file']", self.key_path)
                b.click("#key-file .pf-v5-c-select__menu-item")

            def cancel(self):
                b.click(".pf-v5-c-modal-box__footer button:contains(Cancel)")
                b.wait_not_present(".modal-dialog")

            def create(self):
                b.click(".pf-v5-c-modal-box__footer button:contains(Import)")
                b.wait_not_present(".modal-dialog")

            def verify_frontend(self):
                b.click("button#expand-togglecertificate-0")

                b.wait_in_text("#certificate-0-general-subject", self.subject_name)
                b.wait_in_text("#certificate-0-general-principal", self.principal_name)
                b.wait_in_text("#certificate-0-general-dns", self.dns_name)

                self.test_obj.selectKeyTab(0)
                b.wait_in_text("#certificate-0-key-location", self.key_path)
                self.test_obj.selectCertificateTab(0)
                b.wait_in_text("#certificate-0-cert-location", self.cert_path)

            def verify_backend(self):
                command_output = m.execute(f"getcert list -f {self.cert_path} | grep 'subject:' | awk '{{print $2}}'")
                self.test_obj.assertEqual(command_output, f"CN={self.subject_name}\n")
                command_output = m.execute(f"getcert list -f {self.cert_path} | grep 'dns:' | awk '{{print $2}}'")
                self.test_obj.assertEqual(command_output, f"{self.dns_name}\n")
                command_output = m.execute(f"getcert list -f {self.cert_path} | grep 'principal name:' | awk '{{print $3}}'")
                self.test_obj.assertEqual(command_output, f"{self.principal_name}\n")
                command_output = m.execute(f"getcert list -f {self.cert_path} | grep 'key pair storage:' | awk '{{print $4}}'")
                self.test_obj.assertEqual(command_output, f"type=FILE,location='{self.key_path}'\n")
                command_output = m.execute(f"getcert list -f {self.cert_path} | grep 'certificate:' | awk '{{print $2}}'")
                self.test_obj.assertEqual(command_output, f"type=FILE,location='{self.cert_path}'\n")

            def cleanup(self):
                m.execute(f"selfsign-getcert stop-tracking -f {self.cert_path} -k {self.key_path}")
                b.reload()
                b.enter_page('/certificates')

        cert_path = "/etc/pki/tls/certs/myCert.cert"
        key_path = "/etc/pki/tls/private/myKey.key"
        subject_name = "TEST_HOSTNAME"
        dns_name = "example.com"
        principal_name = "TEST_HOSTNAME@REDHAT.COM"
        # Request certificate which would result with a cert file with specified subject name, dns name and principal name
        m.execute(f"selfsign-getcert request -f {cert_path} -k {key_path} -N 'CN={subject_name}' -D {dns_name} -K {principal_name}")
        testlib.wait(lambda: "MONITORING" in m.execute(f"selfsign-getcert list -f {cert_path}"), delay=1)
        self.addCleanup(self.cleanupFileCertificate, cert_path, key_path)
        # Stop tracking the cert. Files should be left untouched.
        m.execute(f"selfsign-getcert stop-tracking -f {cert_path}")
        b.reload()
        b.enter_page('/certificates')

        # Test importing the file
        # Point of this test is to see if after importing a certificate from certificate file will
        # result in a certificate with correct subject name, dns name and principal name without
        # need to specify it in the UI. That means that importing went properly.
        ImportCertDialog(
            self,
            ca="SelfSign",
            cert_path=cert_path,
            key_path=key_path,
            storage_type="File",
            subject_name=subject_name,
            dns_name=dns_name,
            principal_name=principal_name,
        ).execute()

    def testResubmitCert(self):
        b = self.browser
        m = self.machine

        cert_name = "Server-Cert"
        db_path = "/etc/pki/nssdb"
        dns_name = "example.com"
        m.execute(f"selfsign-getcert request -d {db_path} -n {cert_name} -D {dns_name}")
        self.addCleanup(self.cleanupCertificate, cert_name, db_path)

        self.login_and_go("/certificates")
        # Verify expected heading
        b.wait_in_text(".ct-table-header h3", "Certificates")

        b.wait_in_text("#certificate-0-name", cert_name)
        b.click("button#expand-togglecertificate-0")

        b.wait_not_present("#certificate-0-general-principal")
        b.wait_in_text("#certificate-0-general-dns", dns_name)

        # Resubmit certificate with different signing request parameters
        b.click("#certificate-0-action-kebab button")
        b.click("#certificate-0-resubmit a")
        b.wait_in_text(".pf-v5-c-modal-box .pf-v5-c-modal-box__header .pf-v5-c-modal-box__title", "Resubmit Certificate")

        # Change signing request propertes for resubmit
        subject_name = "CN=TEST_HOSTAME"
        principal_name = "TEST_HOSTNAME@REDHAT.COM"
        b.set_input_text("#subject-name", subject_name)
        b.set_input_text("#principal-name", principal_name)
        b.set_input_text("#dns-name", "")  # Remove DNS name

        old_validity = m.execute(f"selfsign-getcert list -d {db_path} -n {cert_name} | grep 'issued:'").strip()

        # make sure the resubmition is done at least 1 second after the certificate was created
        # This enables us to confirm success of resubmition by looking whetever date of issue of certificate, shown in seconds, changed
        time.sleep(1)
        b.click(".pf-v5-c-modal-box__footer button:contains(Resubmit)")
        b.wait_not_present(".pf-v5-c-modal-box")

        # Check validity time differs which means certificate was resubmitted and renewed
        testlib.wait(lambda: old_validity not in m.execute(f"selfsign-getcert list -d {db_path} -n {cert_name} | grep 'issued:'").strip(), delay=1)

        # Check signing properties are updated
        b.wait_in_text("#certificate-0-general-subject", subject_name)
        b.wait_in_text("#certificate-0-general-principal", principal_name)
        b.wait_not_present("#certificate-0-general-dns")


if __name__ == '__main__':
    testlib.test_main()
