# Enable RPM builds and running integration tests in PRs through https://packit.dev/
# To use this, enable Packit-as-a-service in GitHub: https://packit.dev/docs/packit-as-a-service/
# See https://packit.dev/docs/configuration/ for the format of this file

specfile_path: cockpit-certificates.spec
actions:
  post-upstream-clone:
    - make cockpit-certificates.spec
    # replace Source1 manually, as create-archive: can't handle multiple tarballs
    - make node-cache
    - sh -c 'sed -i "/^Source1:/ s/https:.*/$(ls cockpit-certificates-node*.tar.xz)/" cockpit-certificates.spec'
  # reduce memory consumption of webpack in sandcastle container
  # https://github.com/packit/sandcastle/pull/92
  # https://medium.com/the-node-js-collection/node-js-memory-management-in-container-environments-7eb8409a74e8
  create-archive: make NODE_OPTIONS=--max-old-space-size=500 dist-gzip
jobs:
  - job: tests
    trigger: pull_request
    metadata:
      targets:
      - fedora-34
      - fedora-rawhide
