# Enable RPM builds and running integration tests in PRs through https://packit.dev/
# To use this, enable Packit-as-a-service in GitHub: https://packit.dev/docs/packit-as-a-service/
# See https://packit.dev/docs/configuration/ for the format of this file

specfile_path: cockpit-certificates.spec
srpm_build_deps:
- make
- npm
actions:
  post-upstream-clone:
    - make cockpit-certificates.spec
    # replace Source1 manually, as create-archive: can't handle multiple tarballs
    - make node-cache
    - sh -c 'sed -i "/^Source1:/ s/https:.*/$(ls cockpit-certificates-node*.tar.xz)/" cockpit-certificates.spec'
  create-archive: make dist
jobs:
  - job: tests
    trigger: pull_request
    metadata:
      targets:
      - fedora-all
